### ISSUE TITLE
能提供一个追踪聚合变化的示例么

### ISSUE THREAD

**Issue by victoryw** [codingthought/ddd-aggregate-helper#1]
明白了这几个类的原理
但是没有想明白，你这个AS是如何和Aggregate结合起来用的

by 王岩

**Comment by codingthought** [comment]
好的，我晚点加个例子到测试里。

**Comment by codingthought** [comment]
@victoryw 加了一个用例
https://github.com/codingthought/ddd-aggregate-helper/commit/3827aea39d0870f6c82e7d98cb600a5d1c05e269
